### ISSUE TITLE
지슬학우님 default branch 변경 부탁드립니다

### ISSUE THREAD

**Issue by alsco1234** [Jeeseul/OODP_teamB#4]
repo 소유자인 지슬학우님!
merge라는 최종 브랜치가 생김에 따라 이를 default branch로 변경해주셨으면 합니다.

https://earth-95.tistory.com/86
위 링크 참고하시면 좋을 것 같아 가져왔습니다.

감사합니다.

**Comment by Jeeseul** [comment]
혹시 브랜치 이름이 "merged"인가요? 제가 위 메일만 보고 하다가 merge로 했는데 확인하니까 뭔가 이상해서ㅎㅎ 혹시나해서
여쭙니다!

2022년 5월 16일 (월) 오전 1:16, alsco1234 ***@***.***>님이 작성:

**Comment by alsco1234** [comment]
앗 어떤 부분이 이상한가요?
